import {
  FETCH_PROJECTS,
  FETCH_PROJECT,
  CREATE_PROJECT,
  FETCH_ISSUES,
  FETCH_ISSUE,
  CREATE_ISSUE,
  CLOSE_ISSUE,
  FETCH_COMMENTS,
  FETCH_COMMENT,
  CREATE_COMMENT,
  EDIT_COMMENT,
  DELETE_COMMENT,
  ASSIGN_USER_TO_ISSUE,
  ASSIGN_USER_TO_PROJECT,
  REMOVE_USER_FROM_PROJECT
} from "./types";
import axios from "../axiosConfig";
