export const FETCH_PROJECTS_BY_USER = "FETCH_PROJECTS_BY_USER";
export const FETCH_PROJECT = "FETCH_PROJECT";
export const CREATE_PROJECT = "CREATE_PROJECT";

export const FETCH_ISSUES = "FETCH_ISSUES_BY_PROJECT";
export const FETCH_ISSUE = "FETCH_ISSUE";
export const CREATE_ISSUE = "CREATE_ISSUE";
export const CLOSE_ISSUE = "CLOSE_ISSUE";

export const FETCH_COMMENTS_BY_ISSUE = "FETCH_COMMENTS_BY_ISSUE";
export const FETCH_COMMENT = "FETCH_COMMENT";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const ASSIGN_USER_TO_ISSUE = "ASSIGN_USER_TO_ISSUE";
export const ASSIGN_USER_TO_PROJECT = "ASSIGN_USER_TO_PROJECT";
export const REMOVE_USER_FROM_PROJECT = "REMOVE_USER_FROM_PROJECT";
